import type { PortalDownloadTriggerResult } from "../../core/contracts";
import type { FiledReturnsDownloadTarget } from "./filed-returns-contracts";
import { detectFiledReturnDetailPage } from "./filed-returns-detail-page-guard";
import { verifyFiledReturnsDownloadTarget } from "./filed-returns-download-target";
import { toPortalReturnPeriod } from "./filed-returns-return-period";
import { filedReturnScopeId } from "./filed-returns-return-descriptors";

const GST_RETURNS_ORIGIN = "https://return.gst.gov.in";
const GSTR3B_GENERATED_PDF_PATH = "/returns/auth/api/gstr3b/getgenpdf";

export type FiledGstr3bDirectDownloadAuthorization =
  | { ok: true; ready: { actionId: string; safeSignals: string[] } }
  | { ok: false; downloadTrigger: PortalDownloadTriggerResult };

/**
 * Verifies the visible GSTR-3B target before a single browser-managed request.
 * No portal URL or generated bytes cross the content-script boundary.
 */
export function authorizeFiledGstr3bDirectDownload(
  documentRef: Document,
  target: FiledReturnsDownloadTarget,
): FiledGstr3bDirectDownloadAuthorization {
  const scopeId = filedReturnScopeId(target.returnType);
  if (target.returnType !== "GSTR-3B" || (target.artifactType ?? "PDF") !== "PDF") {
    return blocked(scopeId, ["filed-gstr3b-direct-download-target-rejected"]);
  }
  if (!target.actionId.trim()) {
    return blocked(scopeId, ["filed-gstr3b-direct-download-action-id-missing"]);
  }

  const pageGuard = detectFiledReturnDetailPage(documentRef, target.returnType, "PDF");
  if (!pageGuard.isDetailPage) {
    return {
      ok: false,
      downloadTrigger: {
        connectorId: "gst",
        scopeId,
        state: "candidate-not-found",
        safeSignals: [...pageGuard.safeSignals, "filed-gstr3b-direct-download-detail-unverified"],
        safeMessage:
          "Pack will only start the reviewed GSTR-3B PDF request from the matching filed return detail page.",
        userAction: {
          type: "NAVIGATE_TO_SUPPORTED_PAGE",
          message: "Open the filed GSTR-3B detail page for the selected period, then start Pack again.",
          canResume: true,
        },
      },
    };
  }

  const targetGuard = verifyFiledReturnsDownloadTarget(documentRef, target, pageGuard.safeSignals);
  if (targetGuard) return { ok: false, downloadTrigger: targetGuard };
  if (!toPortalReturnPeriod(target.period, target.financialYear)) {
    return blocked(scopeId, [...pageGuard.safeSignals, "filed-gstr3b-return-period-invalid"]);
  }

  return {
    ok: true,
    ready: {
      actionId: target.actionId,
      safeSignals: [...pageGuard.safeSignals, "filed-gstr3b-direct-download-authorized"],
    },
  };
}

/** Builds the reviewed, target-bound browser request without persisting it. */
export function buildAuthorizedFiledGstr3bDirectDownloadUrl(
  financialYear: string,
  period: string,
): string | null {
  const returnPeriod = toPortalReturnPeriod(period, financialYear);
  if (!returnPeriod) return null;
  const url = new URL(GSTR3B_GENERATED_PDF_PATH, GST_RETURNS_ORIGIN);
  url.search = new URLSearchParams([["rtn_prd", returnPeriod]]).toString();
  return url.toString();
}

function blocked(scopeId: string, safeSignals: string[]): FiledGstr3bDirectDownloadAuthorization {
  return {
    ok: false,
    downloadTrigger: {
      connectorId: "gst",
      scopeId,
      state: "blocked",
      safeSignals,
      safeMessage:
        "Pack could not verify the selected filed GSTR-3B PDF target, so it did not start a browser download.",
    },
  };
}
