import { FILED_RETURNS_MONTHS } from "./filed-returns-scope";
import { ARTIFACT_FAILURE_MESSAGES } from "./artifact-source";

const MAX_DURABLE_SIGNAL_COUNT = 32;

const EXACT_DURABLE_SIGNALS = new Set([
  "browser-download-completed",
  "browser-download-correlation-rejected",
  "browser-download-created",
  "browser-download-danger-pending",
  "browser-download-danger-rejected",
  "browser-download-danger-unknown",
  "browser-download-existence-unknown",
  "browser-download-file-missing",
  "browser-download-interrupted",
  "browser-download-in-progress",
  "browser-download-non-empty",
  "browser-download-not-observed",
  "browser-download-save-dialog-may-be-open",
  "browser-download-search-missing",
  "browser-download-search-unavailable",
  "browser-download-size-unknown",
  "browser-download-state-unconfirmed",
  "browser-download-zero-bytes",
  "detail-summary-modal",
  "detail-summary-modal-close-blocked",
  "detail-summary-modal-close-clicked",
  "detail-summary-modal-close-control-not-found",
  "detail-summary-modal-dismissed",
  "detail-summary-modal-open",
  "download-excel-gstr1-visible",
  "download-excel-gstr2b-visible",
  "download-filed-gstr1-visible",
  "download-filed-gstr2b-visible",
  "download-filed-gstr3b-visible",
  "download-pdf-gstr1-visible",
  "download-pdf-gstr2b-visible",
  "excluded-filing-or-navigation-action",
  "excluded-missing-download-term",
  "excluded-pdf-download",
  "excluded-structured-data-download",
  "excluded-summary-dialog-portal-action",
  "excluded-system-generated-gstr3b",
  "filed-gstr1-controls-pending",
  "filed-gstr1-download-clicked",
  "filed-gstr1-download-status-not-filed",
  "filed-gstr1-download-trigger-ambiguous",
  "filed-gstr1-excel-control-pending",
  "filed-gstr1-excel-no-details-available",
  "filed-gstr1-result-view-auto-attempt-failed",
  "filed-gstr1-result-view-auto-clicked",
  "filed-gstr1-result-view-navigation-pending",
  "filed-gstr1-result-view-user-action-required",
  "filed-gstr1-scope-switch-navigation",
  "filed-gstr1-summary-back-clicked",
  "filed-gstr1-summary-back-unavailable",
  "filed-gstr1-summary-period-mismatch",
  "filed-gstr1-summary-view-clicked",
  "filed-gstr1-summary-view-pending",
  "filed-gstr1-target-bound-detail",
  "filed-gstr3b-download-clicked",
  "filed-gstr3b-download-trigger-ambiguous",
  "filed-gstr3b-direct-download-action-mismatch",
  "filed-gstr3b-direct-download-authorized",
  "filed-gstr3b-direct-download-detail-unverified",
  "filed-gstr3b-direct-download-start-rejected",
  "filed-gstr3b-direct-download-started",
  "filed-gstr3b-direct-download-target-rejected",
  "filed-return-api-result-ambiguous",
  "filed-return-api-result-found",
  "filed-return-api-result-posted",
  "filed-return-api-result-role-status-unavailable",
  "filed-return-api-searched",
  "filed-return-detail-back-clicked",
  "filed-return-detail-back-not-found",
  "filed-return-detail-financial-year-missing",
  "filed-return-detail-period-missing",
  "filed-return-detail-period-unverified",
  "filed-return-detail-type-missing",
  "filed-return-download-clicked",
  "filed-return-download-diagnostics-rejected",
  "filed-return-download-id-persist-failed",
  "filed-return-download-ready",
  "filed-return-download-recovery-checkpoint",
  "filed-return-download-state-persist-failed",
  "filed-return-download-target-mismatch",
  "filed-return-download-trigger-ambiguous",
  "filed-return-durable-status-rejected",
  "filed-return-filter-bound-result-view-clicked",
  "filed-return-filter-bound-result-view-ready",
  "filed-return-filter-candidate-not-found",
  "filed-return-filter-selection-in-progress",
  "filed-return-filters-selected",
  "filed-return-offscreen-blob-url-rejected",
  "filed-return-portal-click-evidence-unavailable",
  "filed-return-positively-not-filed",
  "filed-return-result-row-ambiguous",
  "filed-return-result-row-not-found",
  "filed-return-result-view-clicked",
  "filed-return-result-view-not-found",
  "filed-return-results-visible",
  "filed-return-search-results-pending",
  "filed-return-search-results-unchanged",
  "filed-returns-candidate-clicked",
  "filed-returns-download-attempt-clear-failed",
  "filed-returns-download-id-not-found",
  "filed-returns-download-id-not-persisted",
  "filed-returns-download-intent-persisted",
  "filed-returns-download-manual-review-required",
  "filed-returns-download-reconciled-by-id",
  "filed-returns-download-reconciliation-required",
  "filed-returns-target-local-cleanup-required",
  "filed-returns-download-search-unavailable",
  "filed-returns-download-state-unknown",
  "filed-returns-heading",
  "filed-returns-opfs-clear-failed",
  "filed-returns-opfs-cleared",
  "filed-returns-page-settling",
  "filed-returns-route",
  "filed-returns-run-acknowledged",
  "zip-download-filename-overridden",
  "filed-returns-run-active",
  "filed-returns-run-needs-review",
  "filed-returns-target-cancelled",
  "filed-returns-target-manually-observed",
  "filed-returns-target-bound-candidate-window-interrupted",
  "filed-returns-target-review-clear-failed",
  "filed-returns-target-review-required",
  "financial-year-selected",
  "flow-step-limit-reached",
  "full-fiscal-year-artifact-staging-incomplete",
  "full-fiscal-year-complete",
  "full-fiscal-year-completed-staging-cleanup-failed",
  "full-fiscal-year-download-unconfirmed",
  "full-fiscal-year-final-zip-manual-review",
  "full-fiscal-year-final-zip-retry",
  "full-fiscal-year-local-cleanup-retry",
  "full-fiscal-year-manual-observation-needs-restaging",
  "full-fiscal-year-no-zip-artifacts",
  "full-fiscal-year-opfs-clear-failed",
  "full-fiscal-year-opfs-cleared",
  "full-fiscal-year-opfs-retained",
  "full-fiscal-year-opfs-staged",
  "full-fiscal-year-restaging-required",
  "full-fiscal-year-resume-confirmation-required",
  "full-fiscal-year-retained-staging-scope-conflict",
  "full-fiscal-year-run-active",
  "full-fiscal-year-run-discard-cleanup-failed",
  "full-fiscal-year-run-discarded",
  "full-fiscal-year-run-interrupted",
  "full-fiscal-year-run-needs-action",
  "full-fiscal-year-target-error",
  "full-fiscal-year-target-retry-approved",
  "full-fiscal-year-target-running",
  "full-fiscal-year-zip-artifact-staging-incomplete",
  "full-fiscal-year-zip-cleanup-pending",
  "full-fiscal-year-zip-download-id-missing",
  "full-fiscal-year-zip-download-id-not-found",
  "full-fiscal-year-zip-download-search-unavailable",
  "full-fiscal-year-zip-download-started",
  "full-fiscal-year-zip-download-state-unknown",
  "full-fiscal-year-zip-download-unconfirmed",
  "full-fiscal-year-zip-downloaded",
  "full-fiscal-year-zip-entry-count-mismatch",
  "full-fiscal-year-zip-export-pending",
  "full-fiscal-year-zip-reconciled-by-id",
  "full-fiscal-year-zip-target-state-invalid",
  "gst-login-tab-opened",
  "gst-portal-tab-required",
  "gstr1-dashboard-period-select-found",
  "gstr1-dashboard-period-select-missing",
  "gstr1-dashboard-quarter-select-found",
  "gstr1-dashboard-quarter-select-missing",
  "gstr1-dashboard-root-found",
  "gstr1-dashboard-root-missing",
  "gstr1-dashboard-search-found",
  "gstr1-dashboard-search-missing",
  "gstr1-dashboard-view-unchanged-after-search",
  "gstr1-dashboard-view-unscoped",
  "gstr1-dashboard-year-select-found",
  "gstr1-dashboard-year-select-missing",
  "gstr1-filed-returns-route-mismatched",
  "gstr1-return-dashboard-filter-selection-in-progress",
  "gstr1-return-dashboard-filters-selected",
  "gstr1-return-dashboard-route",
  "gstr1-return-dashboard-search-results-pending",
  "gstr1-detail-heading",
  "gstr1-detail-route",
  "gstr1-dashboard-view-clicked",
  "gstr1-artifact-content-unavailable",
  "gstr1-artifact-period-invalid",
  "gstr1-artifact-response-missing",
  "gstr1-artifact-state-invalid",
  "gstr2b-detail-heading",
  "gstr2b-detail-route",
  "gstr2b-dashboard-view-clicked",
  "gstr2b-artifact-content-unavailable",
  "gstr2b-artifact-period-invalid",
  "gstr2b-artifact-response-missing",
  "gstr2b-artifact-state-invalid",
  "gstr2b-dialog-free-capture-unsupported",
  "gstr2b-download-clicked",
  "gstr2b-portal-blob-download-clicked",
  "gstr2b-return-dashboard-search-results-pending",
  "gstr3b-detail-heading",
  "gstr3b-detail-route",
  "hidden-filed-returns-candidate-clicked",
  "month-selected",
  "no-files-available-for-download",
  "period-selected",
  "quarter-selected",
  "portal-blocked-or-session-expired",
  "portal-scheduled-downtime",
  "portal-system-error",
  "return-dashboard-candidate-clicked",
  "return-dashboard-after-returns-menu",
  "return-dashboard-after-services-menu",
  "return-dashboard-initial-scan",
  "return-filing-period-left-unselected",
  "return-type-selected",
  "safe-dialog-dismissed",
  "no-return-dashboard-candidate",
  "search-clicked",
  "single-period-bundle-artifact-pending",
  "single-period-bundle-artifact-result-unavailable",
  "single-period-bundle-artifact-review-required",
  "single-period-bundle-artifact-running",
  "single-period-bundle-artifact-staged",
  "single-period-bundle-artifact-unavailable",
  "single-period-bundle-ledger-malformed",
  "single-period-bundle-recovered",
  "single-period-bundle-resume-pending",
  "single-period-bundle-revision-conflict",
  "single-period-bundle-running-ambiguous",
  "single-period-bundle-scope-conflict",
  "single-period-bundle-state-persist-failed",
  "single-period-bundle-state-read-failed",
  "single-period-cleanup-checkpoint-failed",
  "single-period-cleanup-checkpoints-cleared",
  "single-period-opfs-cleanup-completed",
  "single-period-opfs-cleanup-required",
  "single-period-opfs-clear-failed",
  "single-period-opfs-cleared",
  "single-period-opfs-retained",
  "single-period-opfs-staged",
  "single-period-zip-cancel-cleanup-failed",
  "single-period-zip-download-reconciliation-required",
  "single-period-zip-download-started",
  "single-period-zip-downloaded",
  "single-period-zip-entry-plan-invalid",
  "single-period-zip-incomplete",
  "single-period-zip-recovery-checkpoint-missing",
  "single-period-zip-retry-cleanup-failed",
  "status-filed",
  "summary-dialog-close",
  "summary-dialog-close-class",
  "summary-dialog-x",
  "text-details-excel-gstr2b",
  "text-download-einvoice-gstr1",
  "text-download-einvoice-gstr2b",
  "text-download-excel-gstr1",
  "text-download-excel-gstr2b",
  "text-download-filed",
  "text-download-filed-gstr1",
  "text-download-filed-gstr2b",
  "text-download-filed-gstr3b",
  "text-download-gstr1",
  "text-download-gstr2b",
  "text-download-gstr3b",
  "text-download-pdf-gstr1",
  "text-download-pdf-gstr2b",
  "text-summary-pdf-gstr2b",
]);

const BROWSER_DOWNLOAD_ERROR_SUFFIXES = new Set([
  "file-blocked",
  "file-failed",
  "file-no-space",
  "file-too-large",
  "file-transient-error",
  "network-disconnected",
  "network-failed",
  "network-invalid-request",
  "network-server-down",
  "network-timeout",
  "network-unauthorized",
  "server-bad-content",
  "server-cert-problem",
  "server-content-length-mismatch",
  "server-cross-origin-redirect",
  "server-failed",
  "server-forbidden",
  "server-no-range",
  "server-precondition",
  "server-unauthorized",
  "user-canceled",
  "user-shutdown",
]);

const CAPTURE_PREFIXES = ["filed-gstr1", "filed-gstr2b", "filed-gstr3b", "gstr2b"];
const CAPTURE_SUFFIXES = [
  "blob-bytes-accepted",
  "blob-capture-failed",
  "blob-content-type-rejected",
  "blob-oversized-rejected",
  "blob-url-fetch-failed",
  "blob-url-fetch-rejected",
  "blob-url-fetch-unavailable",
  "blob-url-observed",
  "blob-zero-byte-rejected",
  "capture-control-ambiguous",
  "capture-control-artifact-mismatch",
  "capture-control-click-threw",
  "capture-control-fingerprint-mismatch",
  "capture-control-not-actionable",
  "capture-control-not-found",
  "capture-hook-install-failed",
  "capture-target-binding-missing",
  "capture-target-binding-invalid",
  "capture-target-evidence-conflict",
  "capture-target-identity-mismatch",
  "capture-target-identity-missing",
  "capture-target-path-mismatch",
  "captured-download-data-url-rejected",
  "chunk-count-rejected",
  "create-object-url-observed",
  "create-object-url-oversized",
  "create-object-url-zero-byte",
  "data-url-content-type-rejected",
  "data-url-observed",
  "data-url-rejected",
  "extension-download-requested",
  "extension-download-start-rejected",
  "extension-download-started",
  "fetch-artifact-response-observed",
  "fetch-content-type-rejected",
  "file-reader-error",
  "file-reader-result-rejected",
  "full-fiscal-year-zip-staged",
  "main-world-capture",
  "main-world-capture-armed",
  "main-world-capture-exception",
  "main-world-capture-result-rejected",
  "main-world-capture-timeout",
  "native-blob-click-suppressed",
  "native-data-click-suppressed",
  "native-https-download-suppressed",
  "native-window-open-suppressed",
  "opfs-chunk-stage-failed",
  "portal-blob-captured",
  "portal-blob-download-captured",
  "portal-data-url-captured",
  "portal-filename-observed",
  "single-period-zip-staged",
  "target-bound-native-blob-click-delegated",
  "unbound-blob-ignored",
  "unbound-blob-url-ignored",
  "unbound-create-object-url-ignored",
  "unbound-create-object-url-no-open-selection",
  "unbound-create-object-url-selection-open-invalid-context",
  "unbound-create-object-url-selection-open-no-context",
  "unbound-create-object-url-selection-open-valid-inactive-context",
  "unbound-data-url-ignored",
  "window-open-observed",
  "xhr-action-binding-ambiguous",
  "xhr-artifact-response-observed",
  "xhr-content-type-rejected",
  "xhr-page-callback-bound-load",
  "xhr-page-callback-bound-loadend",
  "xhr-page-callback-bound-readystatechange",
  "xhr-selection-closed-with-context",
  "xhr-selection-closed-without-context",
];
const CAPTURE_SIGNALS = new Set(
  CAPTURE_PREFIXES.flatMap((prefix) => CAPTURE_SUFFIXES.map((suffix) => `${prefix}-${suffix}`)),
);
const ZIP_SIGNAL_SUFFIXES = [
  "download-checkpoint-incomplete",
  "download-id-invalid",
  "download-id-persist-failed",
  "download-start-rejected",
  "download-started",
  "download-state-persist-failed",
  "download-unconfirmed",
  "downloaded",
  "entry-count-mismatch",
  "entry-plan-invalid",
  "export-failed",
];
const ZIP_SIGNALS = new Set(
  ["full-fiscal-year", "single-period"].flatMap((prefix) =>
    ZIP_SIGNAL_SUFFIXES.map((suffix) => `${prefix}-zip-${suffix}`),
  ),
);
const ZIP_EXPORT_ERROR_CATEGORIES = new Set([
  "opfs-unavailable",
  "zip-empty",
  "zip-failed",
  "zip-invalid-entry",
  "zip-too-large",
]);
const OPFS_STAGE_ERROR_CATEGORIES = new Set([
  "blob-url-failed",
  "clear-failed",
  "invalid-data-url",
  "opfs-unavailable",
  "stage-failed",
  "zip-empty",
  "zip-failed",
  "zip-invalid-entry",
]);

const SCOPED_RETURN_SIGNAL_SUFFIXES = new Set([
  "artifact-unsupported",
  "blob-capture-failed",
  "download-candidate-ambiguous",
  "download-candidate-pre-delegation",
  "download-candidate-missing",
  "download-candidate-not-found",
  "download-clicked",
  "download-ready",
  "extension-download-requested",
  "portal-blob-download-captured",
]);
const ARTIFACT_FAILURE_SIGNALS = new Set([
  "artifact-acquisition-failed",
  "artifact-filed-gstr1-excel-no-details-available",
  ...Object.keys(ARTIFACT_FAILURE_MESSAGES).map((reason) => `artifact-${reason}`),
]);

export function parseDurableFiledReturnsSignals(input: unknown): string[] | null {
  if (!Array.isArray(input) || input.length > MAX_DURABLE_SIGNAL_COUNT) return null;
  if (!input.every((signal): signal is string => typeof signal === "string")) return null;
  if (new Set(input).size !== input.length) return null;
  return input.every(isDurableFiledReturnsSignal) ? [...input] : null;
}

export function isDurableFiledReturnsSignal(signal: string): boolean {
  if (
    EXACT_DURABLE_SIGNALS.has(signal) ||
    CAPTURE_SIGNALS.has(signal) ||
    ZIP_SIGNALS.has(signal) ||
    ARTIFACT_FAILURE_SIGNALS.has(signal)
  ) {
    return true;
  }
  const artifactSignal =
    /^filed-return-artifact-(?:clicked|downloaded|failed|unavailable|unconfirmed):(PDF|JSON|EXCEL)$/.exec(
      signal,
    );
  if (artifactSignal) return true;
  const stagedArtifact = /^(?:full-fiscal-year|single-period)-opfs-staged:(PDF|JSON|EXCEL)$/.exec(
    signal,
  );
  if (stagedArtifact) return true;
  const missingArtifact = /^full-fiscal-year-artifact-not-staged:(PDF|EXCEL)$/.exec(signal);
  if (missingArtifact) return true;
  const periodSignal = /^filed-return-(?:detail|result)-period:([A-Za-z]+)$/.exec(signal);
  if (periodSignal) return FILED_RETURNS_MONTHS.includes(periodSignal[1] as never);
  const downloadIdSignal = /^browser-download-id:(\d{1,10})$/.exec(signal);
  if (downloadIdSignal) return Number.isSafeInteger(Number(downloadIdSignal[1]));
  const browserError = /^browser-download-error-([a-z0-9-]+)$/.exec(signal);
  if (browserError) return BROWSER_DOWNLOAD_ERROR_SUFFIXES.has(browserError[1] ?? "");
  const zipCount =
    /^(full-fiscal-year|single-period)-zip-(?:actual-entry-count|entry-count|expected-entry-count):(\d{1,2})$/.exec(
      signal,
    );
  if (zipCount) {
    const count = Number(zipCount[2]);
    return zipCount[1] === "single-period" ? count <= 3 : count <= 36;
  }
  const opfsStageError = /^(full-fiscal-year|single-period)-opfs-stage-error:([a-z-]+)$/.exec(
    signal,
  );
  if (opfsStageError) return OPFS_STAGE_ERROR_CATEGORIES.has(opfsStageError[2] ?? "");
  const zipExportError = /^(full-fiscal-year|single-period)-zip-export-error:([a-z-]+)$/.exec(
    signal,
  );
  if (zipExportError) return ZIP_EXPORT_ERROR_CATEGORIES.has(zipExportError[2] ?? "");
  const scopedReturnSignal = /^filed-(gstr1|gstr2b|gstr3b)-(.+)$/.exec(signal);
  if (scopedReturnSignal) {
    return SCOPED_RETURN_SIGNAL_SUFFIXES.has(scopedReturnSignal[2] ?? "");
  }
  return [
    "full-fiscal-year-zip-phase:download-intent-persisted",
    "full-fiscal-year-zip-phase:download-observing",
    "full-fiscal-year-zip-phase:download-started",
    "full-fiscal-year-zip-phase:export-retry-pending",
    "full-fiscal-year-zip-phase:legacy-cleanup-pending",
    "pack-error:CONTENT_SCRIPT_UNAVAILABLE",
  ].includes(signal);
}
