import { describe, expect, it } from "vitest";
import {
  DECLINED_ARTIFACT_SIGNALS,
  type DeclinedArtifactSignal,
} from "../../src/connectors/gst/filed-returns-acquisition-diagnostics";
import {
  REFUSAL_BINDING_SIGNALS,
  bindGstr1DetailRefusal,
  bindGstr2bSummaryRefusal,
  declinedArtifactSafeMessage,
  declinedArtifactStep,
  getBoundDeclinedArtifactSignal,
} from "../../src/connectors/gst/filed-returns-declined-artifact";
import { FULL_FISCAL_YEAR_PERIOD } from "../../src/connectors/gst/filed-returns-scope";
import { parseDurableFiledReturnsSignals } from "../../src/connectors/gst/filed-returns-durable-signals";
import { createGstDocument, makeLayoutVisible } from "./filed-returns-flow.test-helpers";
import { normaliseText } from "../../src/connectors/gst/filed-returns-dom";

const SCOPE = {
  artifactType: "PDF_AND_EXCEL",
  financialYear: "2025-26",
  period: "April",
  returnType: "GSTR-2B",
} as const;

function refusalPage(period: string): Document {
  const documentRef = createGstDocument(
    `
      <main>
        <h1>GSTR-2B- AUTO-DRAFTED ITC STATEMENT</h1>
        <p>Financial Year - 2025-26</p>
        <p>Return Period - ${period}</p>
        <div class="alert">GSTR-2B could not be generated by the System.</div>
      </main>
    `,
    "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
  );
  makeLayoutVisible(documentRef);
  return documentRef;
}

describe("a declined artifact cannot be recorded unbound", () => {
  // The guarantee this module exists for, and it is a compile-time one: `declinedArtifactStep`
  // takes proof as its first argument, and the only values of that type come from a binder here.
  // Four emitters learned the check one reported defect at a time; this is what stops a fifth
  // from not learning it. `tsc --noEmit` fails if either line below stops being an error.
  it("will not type-check a result built from a forged binding", () => {
    // @ts-expect-error an object literal does not satisfy the branded binding
    const forged: Parameters<typeof declinedArtifactStep>[0] = { safeSignals: [] };
    expect(forged).toBeDefined();

    const bindingRequired = () =>
      // @ts-expect-error the proof argument cannot be omitted
      declinedArtifactStep({
        signal: "filed-gstr2b-not-generated",
        returnType: "GSTR-2B",
        safeSignals: [],
      });
    expect(bindingRequired).toBeDefined();
  });

  it("refuses to bind a page showing another period, so no result can be built", () => {
    const documentRef = refusalPage("April");

    const binding = bindGstr2bSummaryRefusal(
      documentRef,
      normaliseText(documentRef.body.innerText || documentRef.body.textContent || ""),
      {
        ...SCOPE,
        period: "May",
      },
    );

    expect(binding.bound).toBeNull();
  });

  it("refuses to bind matching text outside the GSTR-2B summary route", () => {
    const documentRef = refusalPage("April");
    documentRef.defaultView?.history.replaceState({}, "", "/returns/auth/filed-returns");

    const binding = bindGstr2bSummaryRefusal(
      documentRef,
      normaliseText(documentRef.body.innerText || documentRef.body.textContent || ""),
      SCOPE,
    );

    expect(binding.bound).toBeNull();
  });

  it("refuses an Excel-only GSTR-1 decline for a PDF target", () => {
    const binding = bindGstr1DetailRefusal(refusalPage("April"), {
      actionId: "synthetic-action",
      artifactType: "PDF",
      financialYear: "2025-26",
      period: "April",
      returnType: "GSTR-1",
    });

    expect(binding.bound).toBeNull();
  });

  it("carries what the guard established into the record", () => {
    const documentRef = refusalPage("April");
    const binding = bindGstr2bSummaryRefusal(
      documentRef,
      normaliseText(documentRef.body.innerText || documentRef.body.textContent || ""),
      SCOPE,
    );
    if (!binding.bound) throw new Error("Expected the visible period to bind.");

    const step = declinedArtifactStep(binding.bound, {
      safeSignals: ["gstr2b-summary-route"],
    });

    expect(getBoundDeclinedArtifactSignal(SCOPE, step.safeSignals)).toBe(
      "filed-gstr2b-not-generated",
    );
    expect(
      getBoundDeclinedArtifactSignal(
        { ...SCOPE, period: FULL_FISCAL_YEAR_PERIOD },
        step.safeSignals,
      ),
    ).toBeNull();
    for (const missing of ["gstr2b-summary-route-verified", "gstr2b-visible-period-verified"]) {
      expect(
        getBoundDeclinedArtifactSignal(
          SCOPE,
          step.safeSignals.filter((signal) => signal !== missing),
        ),
      ).toBeNull();
    }
    expect(
      getBoundDeclinedArtifactSignal(SCOPE, [
        ...step.safeSignals,
        "filed-gstr1-detail-period-verified",
      ]),
    ).toBeNull();
    expect(
      getBoundDeclinedArtifactSignal(SCOPE, [
        ...step.safeSignals,
        "filed-return-positively-not-filed",
      ]),
    ).toBeNull();
    expect(step.state).toBe("blocked");
    expect(step.safeSignals).toContain("gstr2b-summary-route-verified");
    expect(step.safeSignals).toContain("gstr2b-visible-period-verified");
    expect(step.safeSignals).toContain("filed-gstr2b-not-generated");
    // A refusal is terminal, so its signals are persisted. One token the allowlist has never been
    // told about rejects the whole array, which is why the binding signals register by derivation.
    expect(parseDurableFiledReturnsSignals(step.safeSignals)).not.toBeNull();
  });
});

describe("the copy a declined artifact carries", () => {
  it.each(DECLINED_ARTIFACT_SIGNALS)("gives %s its own wording", (signal) => {
    expect(declinedArtifactSafeMessage(signal as DeclinedArtifactSignal)).toMatch(/GST Portal/u);
  });

  it("registers every binding signal for durable storage", () => {
    expect(parseDurableFiledReturnsSignals([...REFUSAL_BINDING_SIGNALS])).not.toBeNull();
  });
});
