import { describe, expect, it } from "vitest";
import { runFiledReturnsDownloadStep } from "../../src/connectors/gst/filed-returns-flow";
import { createGstDocument, makeLayoutVisible } from "./filed-returns-flow.test-helpers";
import { parseDurableFiledReturnsSignals } from "../../src/connectors/gst/filed-returns-durable-signals";

// Captured live. The portal replaces the download controls with this panel, and it keeps rendering
// the period it was last loaded for until a new search settles -- which is what made a stale page
// answer for eleven periods the run never visited.
function createGstr2bNotGeneratedDocument(period: string, financialYear = "2025-26"): Document {
  const documentRef = createGstDocument(
    `
      <main>
        <h1>GSTR-2B- AUTO-DRAFTED ITC STATEMENT</h1>
        <p>Financial Year - ${financialYear}</p>
        <p>Return Period - ${period}</p>
        <p>Generation date -</p>
        <div class="alert">
          Error!
          GSTR-2B could not be generated by the System. Kindly compute your GSTR 2B manually by
          clicking Compute GSTR-2B button available at IMS Dashboard.
        </div>
      </main>
    `,
    "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
  );
  makeLayoutVisible(documentRef);
  return documentRef;
}

describe("GSTR-2B the portal declined to generate", () => {
  // The portal renders this panel where the download control would be, so waiting for that control
  // burns the whole step budget and then stops the fiscal-year run on a period that can never
  // produce an artifact. Recognising the refusal during observation ends the wait, and a blocked
  // step is not continue-able, so the period is recorded absent and the run advances.
  it("records the period whose refusal is actually on screen", async () => {
    const documentRef = createGstr2bNotGeneratedDocument("April");

    const result = await runFiledReturnsDownloadStep(documentRef, {
      artifactType: "PDF_AND_EXCEL",
      financialYear: "2025-26",
      period: "April",
      returnType: "GSTR-2B",
    });

    expect(result.safeSignals).toContain("filed-gstr2b-not-generated");
    expect(result.state).toBe("blocked");
    // `shouldContinueFlow` only continues on a clicked step, so a blocked one stops the wait.
    expect(result.state).not.toBe("clicked");
  });

  it("refuses to answer for a period the visible refusal is not about", async () => {
    // The run has moved on to May; the portal still shows April's panel because no new search has
    // settled. Reading this as May's answer marks a period the run never navigated to.
    const documentRef = createGstr2bNotGeneratedDocument("April");

    const result = await runFiledReturnsDownloadStep(documentRef, {
      artifactType: "PDF_AND_EXCEL",
      financialYear: "2025-26",
      period: "May",
      returnType: "GSTR-2B",
    });

    expect(result.safeSignals).not.toContain("filed-gstr2b-not-generated");
  });

  it("refuses to answer when the visible period cannot be read at all", async () => {
    // Fail closed: an unlabelled panel is "could not determine", never "matches".
    const documentRef = createGstDocument(
      `
        <main>
          <h1>GSTR-2B- AUTO-DRAFTED ITC STATEMENT</h1>
          <div class="alert">GSTR-2B could not be generated by the System.</div>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );
    makeLayoutVisible(documentRef);

    const result = await runFiledReturnsDownloadStep(documentRef, {
      artifactType: "PDF_AND_EXCEL",
      financialYear: "2025-26",
      period: "May",
      returnType: "GSTR-2B",
    });

    expect(result.safeSignals).not.toContain("filed-gstr2b-not-generated");
  });
});

describe("recovering from a stale refusal", () => {
  it("goes back to the dashboard to select the period it was asked for", async () => {
    const documentRef = createGstr2bNotGeneratedDocument("April");
    const back = documentRef.createElement("button");
    back.textContent = "BACK TO DASHBOARD";
    documentRef.querySelector("main")?.append(back);
    let clicked = 0;
    back.addEventListener("click", () => {
      clicked += 1;
    });

    const result = await runFiledReturnsDownloadStep(documentRef, {
      artifactType: "PDF_AND_EXCEL",
      financialYear: "2025-26",
      period: "May",
      returnType: "GSTR-2B",
    });

    // Observable outcome: Pack navigates, rather than answering for a page it never loaded or
    // stalling until the step budget runs out.
    expect(clicked).toBe(1);
    expect(result.state).toBe("clicked");
    expect(result.safeSignals).not.toContain("filed-gstr2b-not-generated");
  });
});

describe("the signals a terminal step leaves behind", () => {
  // A terminal step's signals are persisted. One token the allowlist has never been told about
  // rejects the entire array, which blocks the target -- so a live run recorded "needs review" for
  // all seven periods the portal had plainly refused. The transient "ready" step carried the same
  // token harmlessly for months, because its signals never reach durable state.
  it.each([
    ["the refusal it records", "April"],
    ["the stale page it walks away from", "May"],
  ])("survives storage: %s", async (_label, period) => {
    const documentRef = createGstr2bNotGeneratedDocument("April");

    const step = await runFiledReturnsDownloadStep(documentRef, {
      artifactType: "PDF_AND_EXCEL",
      financialYear: "2025-26",
      period,
      returnType: "GSTR-2B",
    });

    expect(parseDurableFiledReturnsSignals(step.safeSignals)).not.toBeNull();
  });
});
