import { describe, expect, it } from "vitest";
import { detectPostClickBlockedState } from "../../src/connectors/gst/filed-returns-post-click-blocked-state";
import { createGstDocument } from "./filed-returns-flow.test-helpers";

describe("GSTR-2B the portal did not generate", () => {
  // Synthetic fixture: it keeps only the structural outcome, visible identity, and decoy control
  // needed to prove that a bound absence is terminal. It is not captured portal markup.
  const errorPanel = `
    <main>
      <h1>GSTR-2B- AUTO-DRAFTED ITC STATEMENT</h1>
      <p>Financial Year - 2025-26</p>
      <p>Return Period - April</p>
      <div class="alert">GSTR-2B could not be generated by the System.</div>
      <button>BACK TO DASHBOARD</button>
    </main>
  `;

  const target = {
    actionId: "test-action",
    artifactType: "PDF" as const,
    financialYear: "2025-26",
    period: "April",
    returnType: "GSTR-2B" as const,
  };

  it("recognises the portal's own statement that it did not generate one", () => {
    const documentRef = createGstDocument(
      errorPanel,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    const result = detectPostClickBlockedState(documentRef, target, ["gstr2b-summary-route"]);

    expect(result?.state).toBe("blocked");
    expect(result?.safeSignals).toContain("filed-gstr2b-not-generated");
    // The preceding signals are kept, not replaced.
    expect(result?.safeSignals).toContain("gstr2b-summary-route");
  });

  it("does not claim a refusal from a summary page that rendered normally", () => {
    const documentRef = createGstDocument(
      `
        <main>
          <h1>GSTR-2B</h1>
          <button>DOWNLOAD GSTR-2B SUMMARY (PDF)</button>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])).toBeNull();
  });

  // The numbered conditions are advisory text the portal can reword independently of the outcome,
  // so matching them rather than the statement would break on a rewrite that changed nothing.
  it("matches the outcome statement rather than the list of causes", () => {
    const documentRef = createGstDocument(
      `
        <main>
          <p>Financial Year - 2025-26</p>
          <p>Return Period - April</p>
          <div class="alert">
            Error! GSTR-2B could not be generated by the System for this return period.
          </div>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])?.safeSignals).toContain(
      "filed-gstr2b-not-generated",
    );
  });

  // A stale-looking panel must not answer for a target unless its visible identity also binds to
  // that target.
  it("refuses to answer for a period the visible refusal is not about", () => {
    const documentRef = createGstDocument(
      errorPanel,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    const result = detectPostClickBlockedState(documentRef, { ...target, period: "May" }, []);

    expect(result).toBeNull();
  });

  it("refuses to answer on the page's own configuration when nothing visible says so", () => {
    // Same rule as the observation path: a refusal resolves the target outright and no artifact
    // follows to corroborate it, so the inline config cannot stand in for the visible header.
    const documentRef = createGstDocument(
      `
        <main>
          <div class="alert">GSTR-2B could not be generated by the System.</div>
        </main>
        <script>
          var server_urls = {
            "FIN_YEAR": "2025-26",
            "RETURN_PERIOD": "042025",
            "FORM_TYPE": "GSTR2B"
          };
        </script>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])).toBeNull();
  });

  it("refuses to answer when nothing visible names the period at all", () => {
    // Fail closed: an unlabelled panel is "could not determine", never "matches".
    const documentRef = createGstDocument(
      `
        <main>
          <div class="alert">GSTR-2B could not be generated by the System.</div>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])).toBeNull();
  });
});
