import { describe, expect, it } from "vitest";
import { detectPostClickBlockedState } from "../../src/connectors/gst/filed-returns-post-click-blocked-state";
import { createGstDocument } from "./filed-returns-flow.test-helpers";

describe("GSTR-2B the portal did not generate", () => {
  // Captured live on 2026-09-10. The summary route renders this panel instead of a downloadable
  // GSTR-2B. It is a state of the return, not a fault in reaching it, and retrying cannot change
  // it within a run -- so it is recorded as an absence rather than left as a stall.
  const errorPanel = `
    <main>
      <h1>GSTR-2B- AUTO-DRAFTED ITC STATEMENT</h1>
      <p>Financial Year - 2025-26</p>
      <p>Return Period - April</p>
      <p>Generation date -</p>
      <div class="alert">
        Error!
        GSTR-2B could not be generated by the System. Kindly compute your GSTR 2B manually by
        clicking Compute GSTR-2B button available at IMS Dashboard.
        Attention: System will not generate GSTR 2B for the current return period in any one of
        the following circumstances:
        i. There are no records to generate GSTR 2B for the current return period
        ii. GSTR 3B of last return period is not filed till GSTR 2B generation date
        iii. You are a QRMP taxpayer and current return period is not a quarter ending month
      </div>
      <button>BACK TO DASHBOARD</button>
    </main>
  `;

  const target = {
    actionId: "test-action",
    artifactType: "PDF" as const,
    financialYear: "2025-26",
    period: "April",
    returnType: "GSTR-2B" as const,
  };

  it("recognises the portal's own statement that it did not generate one", () => {
    const documentRef = createGstDocument(
      errorPanel,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    const result = detectPostClickBlockedState(documentRef, target, ["gstr2b-summary-route"]);

    expect(result?.state).toBe("blocked");
    expect(result?.safeSignals).toContain("filed-gstr2b-not-generated");
    // The preceding signals are kept, not replaced.
    expect(result?.safeSignals).toContain("gstr2b-summary-route");
  });

  it("does not claim a refusal from a summary page that rendered normally", () => {
    const documentRef = createGstDocument(
      `
        <main>
          <h1>GSTR-2B</h1>
          <button>DOWNLOAD GSTR-2B SUMMARY (PDF)</button>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])).toBeNull();
  });

  // The numbered conditions are advisory text the portal can reword independently of the outcome,
  // so matching them rather than the statement would break on a rewrite that changed nothing.
  it("matches the outcome statement rather than the list of causes", () => {
    const documentRef = createGstDocument(
      `
        <main>
          <p>Financial Year - 2025-26</p>
          <p>Return Period - April</p>
          <div class="alert">
            Error! GSTR-2B could not be generated by the System for this return period.
          </div>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])?.safeSignals).toContain(
      "filed-gstr2b-not-generated",
    );
  });

  // The summary route does not change per period, and the panel outlives the period it was loaded
  // for. Resolving a target from the return type plus whatever text is on the body lets one
  // period's refusal answer for every later period a run asks about -- which is how a live run
  // recorded eleven months it never navigated to, on the observation path next door.
  it("refuses to answer for a period the visible refusal is not about", () => {
    const documentRef = createGstDocument(
      errorPanel,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    const result = detectPostClickBlockedState(documentRef, { ...target, period: "May" }, []);

    expect(result).toBeNull();
  });

  it("refuses to answer when nothing visible names the period at all", () => {
    // Fail closed: an unlabelled panel is "could not determine", never "matches".
    const documentRef = createGstDocument(
      `
        <main>
          <div class="alert">GSTR-2B could not be generated by the System.</div>
        </main>
      `,
      "https://gstr2b.gst.gov.in/gstr2b/auth/gstr2b/summary",
    );

    expect(detectPostClickBlockedState(documentRef, target, [])).toBeNull();
  });
});
